### ISSUE TITLE
To-Do-List release 1.0.0

### ISSUE THREAD

**Issue by julianpoemp** [IPS-LMU/octra-api#1]
- [ ] Export type definitions for other typescript projects
- [ ] **(API method)**: refreshApptoken
- [ ] **(API method)**: changeUser
- [ ] **(API method)**: continueTranscript
- [ ] **(API method)**: finishTranscript
- [ ] **(API method)**: removeTranscript
- [ ] **(API method)**: listProjects
- [ ] **(API method)**: getProjectConfiguration
- [ ] **(API method)**: getTranscriptionGuidelines
